[package]
name = "ml-reinforcement-learning-group-based-optimization"
version = "0.1.0"
edition = "2021"

[lib]
name = "ml_reinforcement_learning_group_based_optimization"
path = "src/lib.rs"

[dependencies]
