[package]
name = "ml-deep-learning-vanishing-exploding-gradients"
version = "0.1.0"
edition = "2021"

[lib]
name = "ml_deep_learning_vanishing_exploding_gradients"
path = "src/lib.rs"

[dependencies]
