[package]
name = "ml-reinforcement-learning-exploration-exploitation"
version = "0.1.0"
edition = "2021"

[lib]
name = "ml_reinforcement_learning_exploration_exploitation"
path = "src/lib.rs"

[dependencies]
